### ISSUE TITLE
Remove NotNeg

### ISSUE THREAD

**Issue by hgntn** [objeck/objeck-lang#169]
Why there is `NotNeg` from the first place? We already have `IsNeg`. `NotNeg()` is anything shorter than `<>IsNeg()`?

**Comment by objeck** [comment]
Ok, no strong opinion on the matter

**Comment by tn1997tn** [comment]
Yep. I think `NotNeg` should be removed because it's redundant. But if I was @objeck, I will choose the easier and most straight forward path that is renaming `IsNeg` to `IsNegative` and done. The OP complained about the inconsistency of the API. But I found  the API is pretty consistent as the long wordy syntax was used everywhere. Only `IsNeg` and `NotNeg` as I found use abbreviated form.

**Comment by objeck** [comment]
Released in 9fc3c7e
