### ISSUE TITLE
Generics?

### ISSUE THREAD

**Issue by refi64** [objeck/objeck-lang#2]
I'm guessing that this was an explicit non-goal...

but this seems rather ugly:

```
result := reserved->Find(string)->As(String);
```

In my opinion, it'd be really easy to end up with a mismatched `As` somewhere.

I'm also kind of curious as to why `StringMap`'s find needs explicit casts to `String`.

**Comment by objeck** [comment]
Generics is a logical addition to the language just haven't had time to fully implement the feature. It's been prototyped in the past.

Having casts on the right-hand side of an expression was a design goal
```
result := reserved->Find(string)->As(String);
```
instead of
```
result := (String)reserved->Find(string);
```

The ```StringMap``` class uses ```String``` instances as keys and ```Base``` instances (i.e. any object type) as values. Keys don't need to be cast however values do.

**Comment by kirbyfan64** [comment]
I wasn't saying `As` on the right-hand-side was a bad thing. It just might be easy to use the wrong type when you have to explicitly cast to the value type. It also loses quite a bit of type safety over generics.

**Comment by kirbyfan64** [comment]
As an example, I wrote a BF interpreter in Objeck. Because I needed to continuously box and unbox the integers in the bracket map, the result was really

**Comment by kirbyfan64** [comment]
Wrong button!

**Comment by objeck** [comment]
Hi Ryan, I'm working on a new major release and will looking at this.

**Comment by objeck** [comment]
No plans to implement generics in the near future

**Comment by objeck** [comment]
Going to revisit this

**Comment by objeck** [comment]
Going to add support for generic programming in the upcoming 5.x release.

**Comment by objeck** [comment]
Work is being done on the 'generic_types' branch

**Comment by objeck** [comment]
Feature code merged into main. Debugging, refactoring and stabilizing while rebuilding collection libraries.

vector example: https://github.com/objeck/objeck-lang/blob/master/programs/test/generics/debug7.obs

tree example: https://github.com/objeck/objeck-lang/blob/master/programs/test/generics/debug8.obs

**Comment by objeck** [comment]
@refi64 can you share your BF code? 

Want to understand why it's so slow. Going to add boxing and unboxing as well in 5.0.x. Wrote a BF interpreter for Rosetta code while back (https://rosettacode.org/wiki/Execute_Brain****#Objeck) wondering if there's other factors that are slowing down the code.

**Comment by refi64** [comment]
Unfortunately it met a sad fate when I accidentally wiped my hard drive, but maybe I can try to write it again.

That implementation built up a map of brackets prior to the execution, but since the ints had to be in an object it slowed down the retrieval.

**Comment by objeck** [comment]
Thanks @refi64, generics (and type boxing) are around the corner as I'm starting to glue the piece/parts of the compiler back together. Luckily 95% of the code changes were isolated to the contextual analysis engine and using type erasure limited the probability breaking existing functionally.  

Going to need a few weeks to test and validate the changes. Next will be rebuilding the class libraries. As all the changes have merged there's no turning back now!

**Comment by objeck** [comment]
Hi all, since I was adding support for generics figured I'd also add support boxing/unboxing. 

Doing both in tandem proved to be more work then I thought.

The process and challanges:
* Coded initial support for generics
* Added boxing support
* Broke support for generics
* Disabled the generic code and refactored boxing
* Rewrote  the generic code using the original code as a guide post
* Tested debugged, things stabilized nicely
* Build the new bundle 'Collection.Generic' from a port of 'Collection' bundle

Result: https://github.com/objeck/objeck-lang/blob/master/core/compiler/lib_src/gen_collect.obs

Testing is going well, no major issues found and code ported is fairly complex.

**Comment by objeck** [comment]
Collection.Generic: https://www.objeck.org/doc/api/index.html

**Comment by objeck** [comment]
Feature added: https://github.com/objeck/objeck-lang/releases/tag/v5.0.0
