### ISSUE TITLE
Embed into C++ application like Quirrel?

### ISSUE THREAD

**Issue by 2dpdlja496or43iq** [objeck/objeck-lang#219]

**Comment by objeck** [comment]
I am unfamiliar with Quirrel; however, the compiler and runtime can be embedded into other C/C++ applications.

**Comment by 2dpdlja496or43iq** [comment]
> I am unfamiliar with Quirrel; however, the compiler and runtime can be embedded into other C/C++ applications.

Tutorial?

**Comment by objeck** [comment]
What are you trying to do? Please go to the Discord channel; we can chat there.

**Comment by iahunq** [comment]
Wow, it's possible? Please tell me how @objeck 

p/s: I don't know what the OP wanted to do either but my in imagination is something like reverse JNI, calling Java from C++ (instead of normal JNI, calling C++ from Java). Or maybe something like Lua that could be embedded into C++ to provide scripting capacity, e.g: MPV used Lua to allow users writing plugins in Lua instead of C++.
