### ISSUE TITLE
Compile to a native Windows program.

### ISSUE THREAD

**Issue by Spoiledpay** [objeck/objeck-lang#408]
Hello!
Can we or is there any way to write the program and then compile it into a native Windows program, without having to use the VM? Would it be a native windows HelloWord.exe? If so, what would be the steps to make this possible?

**Comment by tqo50396** [comment]
See here: https://objeck.org/getting_started.html#create_portable

Disclaimer: Never worked for me!

**Comment by objeck** [comment]
If you run into issues, let me know.

**Comment by objeck** [comment]
@Spoiledpay, what type of functionality are you looking for? Objeck supports natively launching an executable that invokes the VM to run binaries. Objeck does not compile programs into target-specific machine code; instead uses JIT compilers at runtime.

**Comment by Spoiledpay** [comment]
It was reported that it works in JIT, in this case is a 64-bit JIT compiler resulting in a Windows and Linux runtime exception?
And can we consider that it doesn't compile natively like GCC or like a .Net framework?
In this case, we have many steps to generate an .exe packaged executable, we could generate something simpler for the user for Linux and Windows, and increase acceptance,
Because all languages ​​need developers.

And Additional examples of GUI usage with SDL or Gnome or Native Windows window. Could we achieve this in the future, more examples of the language?

**Comment by objeck** [comment]
> It was reported that it works in JIT, in this case is a 64-bit JIT compiler resulting in a Windows and Linux runtime exception?

I am able to run the code on Windows and Linux without any runtime errors. If you see error reported please notify me.

And can we consider that it doesn't compile natively like GCC or like a .Net framework? 

Objeck does not support AOT compilation. The binary that is produced launches the VM.

In this case, we have many steps to generate an .exe packaged executable, we could generate something simpler for the user for Linux and Windows, and increase acceptance, Because all languages ​​need developers.

Thanks for the feedback, I have not looked at this in a while. I will look at simplifications over the weekend.

> 
> And Additional examples of GUI usage with SDL or Gnome or Native Windows window. Could we achieve this in the future, more examples of the language?

Please find inline above
