### ISSUE TITLE
Support serializing/deserializing of JSON to/from Objeck collections

### ISSUE THREAD

**Issue by ghost** [objeck/objeck-lang#422]
This is one of the very handy feature of Newtonsoft.Json.

https://www.newtonsoft.com/json/help/html/Introduction.htm

**Comment by objeck** [comment]
I like the way Python (and JavaScript) handles JSON. Objeck currently handles JSON like Java does. Some of this is due to the late binding of datatypes (i.e., cast in Java) specific get method in Objeck. I am looking into this further and plan to incorporate more Python-like features.

**Comment by objeck** [comment]
I am going to close this. The issue here is that collections are generic. 

The current implementation abstracts concrete types via the ``JsonElement`` class. From there, one can request specific types: ARRAY, OBJECT, STRING, etc. I looked at Java, and they took a similar approach to Objeck; however, there are many Java parsing frameworks out today.
